### ISSUE TITLE
Calling the `appcast` stanza is deprecated

### ISSUE THREAD

**Issue by vintagesucks** [nicoverbruggen/homebrew-cask#1]
During `brew update`:

```sh
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the nicoverbruggen/cask tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/nicoverbruggen/homebrew-cask/Casks/phpmon.rb:9
```

---

https://github.com/nicoverbruggen/homebrew-cask/blob/6c4cc9fcfe5599b578278dc66d804a9c44d6f4b1/Casks/phpmon.rb#L9

https://github.com/nicoverbruggen/homebrew-cask/blob/6c4cc9fcfe5599b578278dc66d804a9c44d6f4b1/Casks/phpmon-dev.rb#L9

**Comment by nicoverbruggen** [comment]
Thank you for reporting!

**Comment by nicoverbruggen** [comment]
Should be fixed now, I've removed the stanza since it wasn't required or used anyway.
